### ISSUE TITLE
Documentation and Demo Pages Gone

### ISSUE THREAD

**Issue by skibulk** [Mtillmann/mootools-canvas-lib#4]
Can you post the documentation and demo pages to this repository? They have disappeared from your old links.

**Comment by Mtillmann** [comment]
I will try to find them in some backup

**Comment by SergioCrisostomo** [comment]
Meanwhile: https://web.archive.org/web/20120129174238/http://forvar.de/js/mcl/docs.CANVAS.html

**Comment by Mtillmann** [comment]
Awesome, thanks man! (y)

**Comment by Mtillmann** [comment]
I am closing this. Thank you @SergioCrisostomo ! Also @skibulk , you should probably look around for a more modern solution!
